spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.30.120:3306/zgoodb_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: zgoodb_dev
    password: 1234
  thymeleaf:
    cache: false
    # prefix: classpath:/templates/
    # suffix: .html


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
    defer-datasource-initialization: false  # hibernate 초기화 후 SQL 스크립트 실행
  
  sql:
    init:
      mode: never
      platform: mariadb
      continue-on-error: true
      encoding: UTF-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: 300000  # 5분 (밀리초)  

  devtools:
    livereload:
      enabled: true

# server 설정은 최상위 레벨에 추가
server:
  port: 9080
  tomcat:
    max-http-form-post-size: 50MB
    connection-timeout: 300000  # 5분 (밀리초)
  servlet:
    session:
      timeout: 1800 # 30분 - 초 설정
    context-path:


logging:
  level:
    p6spy: ERROR
    org.hibernate.type: trace
  config: classpath:logback-spring.xml
  


# WEB - WAS Ajp 방화벽 (내장 톰캣 설정 시) - (짐작)
fwaccess:
  properties:
    tomcat_ajp_protocol: AJP/1.3
    tomcat_ajp_port: 9009
    tomcat_ajp_redirect_port: 9443
    tomcat_ajp_address: 192.168.30.120
    tomcat_ajp_allowed_request_attributes_pattern: .*
    tomcat_ajp_enable: true

file:
  dir: /app/cpos/files
  img: /app/cpos/images