spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydatabase?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # url: jdbc:log4jdbc:mysql://127.0.0.1:3306/mydatabase?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  thymeleaf:
    cache: false
    # prefix: classpath:/templates/
    # suffix: .html
  hikari:
    shutdown-timeout: 10000
  mail:
    host: smtp.naver.com
    port: 465
    username: aceopkm@naver.com
    password: 43NXXLSZG37G
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          ssl:
            enable: true
    default-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
    defer-datasource-initialization: false  # hibernate 초기화 후 SQL 스크립트 실행
  
  sql:
    init:
      mode: never
      platform: mysql
      continue-on-error: true
      encoding: UTF-8
      # 중요: Hibernate 초기화 후 SQL 스크립트 실행
      schema-locations: classpath:schema.sql  # 필요한 경우
      data-locations: classpath:data.sql

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: 300000  # 5분 (밀리초)  

# 톰캣 설정
server:
  tomcat:
    max-http-form-post-size: 50MB
    connection-timeout: 300000  # 5분 (밀리초)
  servlet:
    session:
      timeout: 30m  # 30분

# p6spy 설정 추가
decorator:
  datasource:
    p6spy:
      enable-logging: false  # p6spy 로깅 비활성화

logging:
  level:
    org.hibernate.type: trace
  config: classpath:logback-spring.xml


# WEB - WAS Ajp 방화벽 (내장 톰캣 설정 시) - (짐작)
fwaccess:
  properties:
    tomcat_ajp_protocol: AJP/1.3
    tomcat_ajp_port: 9009
    tomcat_ajp_redirect_port: 9443
    tomcat_ajp_address: 192.168.30.120
    tomcat_ajp_allowed_request_attributes_pattern: .*
    tomcat_ajp_enable: false

file:
  dir: C:/zgoo/files/
  img: C:/zgoo/images/