spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.30.120:3306/zgoodb_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: zgoodb_dev
    password: 1234
  thymeleaf:
    cache: false
    # prefix: classpath:/templates/
    # suffix: .html
  hikari:
    shutdown-timeout: 10000


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update  # 애플리케이션 시작 시 스키마 자동 생성
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        # 다국어 지원을 위한 컬럼 추가 설정
        hbm2ddl:
          auto: update
    # defer-datasource-initialization: true
    defer-datasource-initialization: false
  
  sql:
    init:
      # mode: always  # SQL 초기화 스크립트 항상 실행
      mode: never  # SQL 초기화 스크립트 항상 실행
      platform: mariadb
      continue-on-error: true
      encoding: UTF-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: 300000  # 5분 (밀리초)  

  devtools:
    livereload:
      enabled: true

  # 국제화 설정 추가
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
    cache-duration: 3600

  # 메일 설정 추가
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# server 설정은 최상위 레벨에 추가
server:
  port: 9080
  tomcat:
    max-http-form-post-size: 50MB
    connection-timeout: 300000  # 5분 (밀리초)
  servlet:
    session:
      timeout: 1800 # 30분 - 초 설정
    context-path:

# p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

# 로그 설정
logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: INFO  # Hibernate 로그 레벨을 INFO로 설정하여 스키마 변경 모니터링
    p6spy: INFO  # p6spy 로그 레벨을 INFO로 설정
    zgoo.cpos: INFO
    org.springframework.web.servlet.i18n: DEBUG
    org.springframework.context.support: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG  # SQL 초기화 스크립트 실행 로그
  


# WEB - WAS Ajp 방화벽 (내장 톰캣 설정 시) - (짐작)
fwaccess:
  properties:
    tomcat_ajp_protocol: AJP/1.3
    tomcat_ajp_port: 9009
    tomcat_ajp_redirect_port: 9443
    tomcat_ajp_address: 192.168.30.120
    tomcat_ajp_allowed_request_attributes_pattern: .*
    tomcat_ajp_enable: false

file:
  dir: /app/cpos/files
  img: /app/cpos/images