spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydatabase?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # url: jdbc:log4jdbc:mysql://127.0.0.1:3306/mydatabase?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  thymeleaf:
    cache: false
    # prefix: classpath:/templates/
    # suffix: .html


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
  
  sql:
    init:
      mode: always
      platform: mysql
      continue-on-error: true
      encoding: UTF-8


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.hibernate.stat: debug


# WEB - WAS Ajp 방화벽 (내장 톰캣 설정 시) - (짐작)
fwaccess:
  properties:
    tomcat_ajp_protocol: AJP/1.3
    tomcat_ajp_port: 9009
    tomcat_ajp_redirect_port: 9443
    tomcat_ajp_address: 192.168.30.120
    tomcat_ajp_allowed_request_attributes_pattern: .*
    tomcat_ajp_enable: true

file:
  dir: C:/Users/N-426/Desktop/store/